version: '3'

services:

  django-app:
    build: ./django-app/
    container_name: django
    restart: always
    depends_on:
      - db
    networks:
      - my-network
    ports:
      - "8000:8000"
    env_file:
      - ./.env

  db:
    container_name: postegres-db
    image: postgres:15
    restart: always
    env_file:
      - ./.env
    networks:
      - my-network
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/

networks:
  my-network:
    driver: bridge
