version: '3.8'

networks:
  my-network:
    driver: bridge

services:

  django-app:
    build: ./django-app/
    container_name: django
    restart: always
    depends_on:
      - db
    networks:
      - my-network
    ports:
      - "8000:8000"
    env_file:
      - ./.env

  db:
    build: ./postgre/
    restart: always
    env_file:
      - ./.env
    networks:
      - my-network
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:

