CREATE DATABASE "$POSTGRES_DB";
CREATE ROLE "$POSTGRES_USER" WITH LOGIN PASSWORD 'password_very_strong2';
GRANT ALL PRIVILEGES ON DATABASE "$POSTGRES_DB" TO "$POSTGRES_USER";
GRANT CREATE ON SCHEMA public To "$POSTGRES_USER";
ALTER USER "$POSTGRES_USER" WITH SUPERUSER;

